# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.9.2"

package:
  name: dacite
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dacite/dacite-${{ version }}.tar.gz
  sha256: 6ccc3b299727c7aa17582f0021f6ae14d5de47c7227932c47fec4cdfefd26f09

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - dataclasses

tests:
  - python:
      imports:
        - dacite
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/konradhalas/dacite
  license: MIT
  license_file: LICENSE
  summary: Simple creation of data classes from dictionaries.
  description: |
    Simple creation of data classes from dictionaries.

extra:
  recipe-maintainers:
    - rxm7706
    - mands
